/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _HBProj4_LoadingObject_TryWithResource;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
